// Inlines the committed critical-CSS artifact (server/assets/critical.css,
// generated by scripts/extract-critical-css.mjs) and defers the full entry
// stylesheet with the same media="print" swap used for noncritical.css.
// A stale artifact self-heals: anything it misses is styled when the full
// sheet arrives (~0.5 s on Slow 4G). No-op in dev, when the artifact is
// missing, or on any internal error — this plugin must never break a render.
export default defineNitroPlugin((nitroApp) => {
  if (import.meta.dev) return;

  let criticalPromise = null;
  const loadCritical = () =>
    (criticalPromise ??= useStorage("assets:server")
      .getItem("critical.css")
      .then((raw) => {
        const css = typeof raw === "string" ? raw : raw ? raw.toString() : "";
        return css.trim().length > 0 ? css : null;
      })
      .catch(() => null));

  // Matches the rendered entry stylesheet link verbatim, e.g.
  // <link rel="stylesheet" href="/_nuxt/entry.BCjVBijJ.css" crossorigin>
  // (verified against actual SSR output: the link carries a bare
  // `crossorigin` attribute with no value, and is embedded inline among a
  // run of other <style> tags within a single html.head[] string, not on
  // its own — hence a non-anchored match-and-replace rather than an exact
  // array-entry comparison).
  const ENTRY_LINK_RE =
    /<link rel="stylesheet"[^>]*href="(\/_nuxt\/entry\.[^"]+\.css)"[^>]*>/;

  nitroApp.hooks.hook("render:html", async (html) => {
    try {
      const critical = await loadCritical();
      if (!critical) return;
      for (let i = 0; i < html.head.length; i++) {
        const match = html.head[i].match(ENTRY_LINK_RE);
        if (!match) continue;
        const href = match[1];
        html.head[i] = html.head[i].replace(
          ENTRY_LINK_RE,
          `<style data-critical>${critical}</style>` +
            `<link rel="stylesheet" href="${href}" media="print" onload="this.media='all'" crossorigin>` +
            `<noscript><link rel="stylesheet" href="${href}" crossorigin></noscript>`
        );
        return; // exactly one entry stylesheet
      }
    } catch {
      // degrade to the untouched head
    }
  });
});
